# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  jobs:
    pre_install:
          # Clone the repository
      - git clone https://github.com/empriselab/RCareWorld.git
      - ls
      # Navigate into the directory
      - cd RCareWorld/pyrcareworld/ && ls
      # Install Python dependencies from requirements.txt
      - pip install -r RCareWorld/pyrcareworld/requirements.txt
      # Install the package in editable mode
      - cd RCareWorld/pyrcareworld/ && pip install -e .
      # Install additional requirements for docs
      - pip install -r docs/requirements.txt
      - cd ../..
      - ls

    post_install:
      - sphinx-apidoc -o ./docs/api ./pyrcareworld ./pyrcareworld/pyrcareworld/demo/*

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
   - pdf
   - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#    - method: pip
#      path: .
#    - requirements: docs/requirements.txt

# branches:
#   only:
#     - main
#     - stable