# Use the official Python 3.10 slim image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Install git
RUN apt-get update && \
    apt-get install -y git && \
    apt-get install -y git curl libgl1-mesa-glx libglib2.0-0 && \
    apt-get clean

# Install Git Large File Storage
RUN apt-get update && \
    apt-get install -y curl && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get install -y git-lfs && \
    apt-get clean && \
    git lfs install

# Clone the specified GitHub repository
RUN git clone https://github.com/empriselab/RCareWorld.git
WORKDIR /app/RCareWorld

# Switch to the competition-specific branch
RUN git checkout phy-robo-care

# Install Python dependencies from requirements.txt
WORKDIR /app/RCareWorld/pyrcareworld

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -e .
RUN pip install opencv-python


WORKDIR /app/RCareWorld/template/docker-template

# Command to run the test_bathing.py script on container start
CMD ["./run_python.shell"]
