name: CI Checks

on: [push]

jobs:
  unit-tests:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: anaconda-client-env
          environment-file: etc/example-environment-caching.yml
    - name: Install dependencies
      run: |
        conda create -n rcareworld python=3.10
        conda activate rcareworld
        cd RCareWorld/pyrcareworld
        pip install -r requirements.txt
        pip install -e .
        pip uninstall numpy
        conda install numpy
    - name: Verify that installation works
      run: |
        cd RCareWorld/template
        python test_bathing.py
